name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dbus
      run: sudo apt-get install dbus libdbus-1-dev libdbus-glib-1-dev
    - name: Build
      run: cargo build --verbose
